export interface Image {
    id: string;
    src: string;
  }
  
  export const IMAGES: Image[] = [
    { id: "0", src: require("./images/AlejandroGarnacho.jpeg") },
    { id: "1", src: require("./images/AlissonBecker.jpeg") },
    { id: "2", src: require("./images/AndreOnana.jpeg") },
    { id: "3", src: require("./images/AnthonyMartial.jpeg") },
    { id: "4", src: require("./images/Antony.jpeg") },
    { id: "5", src: require("./images/BernardoSilva.jpeg") },
    { id: "6", src: require("./images/BrunoFernandes.jpeg") },
    { id: "7", src: require("./images/BukayoSaka.jpeg") },
    { id: "8", src: require("./images/ChristianEriksen.png") },
    { id: "9", src: require("./images/CodyGakpo.png") },
    { id: "10", src: require("./images/CristianoRonaldo.jpeg") },
    { id: "11", src: require("./images/DavidBeckham.jpeg") },
    { id: "12", src: require("./images/DaviddeGea.jpeg") },
    { id: "13", src: require("./images/EdenHazard.jpeg") },
    { id: "14", src: require("./images/EdersonMoraes.webp") },
    { id: "15", src: require("./images/ErlingHaaland.png") },
    { id: "16", src: require("./images/GabrielMartinelli.jpeg") },
    { id: "17", src: require("./images/HarryKane.webp") },
    { id: "18", src: require("./images/HarryMaguire.jpeg") },
    { id: "19", src: require("./images/JackGrealish.jpeg") },
    { id: "20", src: require("./images/JadonSancho.png") },
    { id: "21", src: require("./images/JulianAlvarez.webp") },
    { id: "22", src: require("./images/KaiHarvertz.jpeg") },
    { id: "23", src: require("./images/Kaka.jpeg") },
    { id: "24", src: require("./images/KarimBenzama.png") },
    { id: "25", src: require("./images/KevindeBruyne.jpeg") },
    { id: "26", src: require("./images/KyleWalker.webp") },
    { id: "27", src: require("./images/LionelMessi.png") },
    { id: "28", src: require("./images/LisandroMartinez.png") },
    { id: "29", src: require("./images/LukeShaw.jpeg") },
    { id: "30", src: require("./images/MarcusRashford.jpeg") },
    { id: "31", src: require("./images/MartinOdegaard.jpeg") },
    { id: "32", src: require("./images/MasonMount.webp") },
    { id: "33", src: require("./images/MohamedSalah.png") },
    { id: "34", src: require("./images/NathanAke.jpeg") },
    { id: "35", src: require("./images/PaulPogba.jpeg") },
    { id: "36", src: require("./images/PhilFoden.webp") },
    { id: "37", src: require("./images/RaphaelVarane.avif") },
    { id: "38", src: require("./images/RasmusHojlund.jpeg") },
    { id: "39", src: require("./images/Richarlison.jpeg") },
    { id: "40", src: require("./images/RobertLewandowski.png") },
    { id: "41", src: require("./images/Rodri.png") },
    { id: "42", src: require("./images/Ronaldinho.webp") },
    { id: "43", src: require("./images/Ronaldodelima.png") },
    { id: "44", src: require("./images/SergioRamos.jpeg") },
    { id: "45", src: require("./images/SofyanAmrabat.webp") },
    { id: "46", src: require("./images/SonHeungmin.png") },
    { id: "47", src: require("./images/TrentAlexanderArnold.jpeg") },
    { id: "48", src: require("./images/VirgilvanDijk.png") },
    { id: "49", src: require("./images/WayneRooney.jpeg") },
    { id: "50", src: require("./images/Zinchenko.jpeg") },
    { id: "51", src: require("./images/ZinedineZidane.jpeg") },
    { id: "52", src: require("./images/ZlatanIbrahimovic.jpeg") },
  ];
  